"use client"


import Layout from "@/components/layout/Layout";
import 'normalize.css';
import "./globals.css";
import { yekan } from "@/utils/font";
import i18n from "@/core/i18n";
// import { ThemeProvider  , Button} from "@material-tailwind/react";


// export const metadata = {
//   title: "رابین صنعت دایان",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      {/* <ThemeProvider> */}
        <body  className={yekan.className}>
          <Layout>
          {children}
          </Layout>
        </body>
      {/* </ThemeProvider> */}
      
    </html>
  );
}



 
// export { ThemeProvider, Button };